spring.application.name=ticket-system

#Database Connfiguration
server.port = 8089
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_system_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jackson.time-zone=Asia/Jakarta