spring.application.name=ticket-system

#Database Configuration
server.port=8089
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/ticket_system_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.jackson.time-zone=Asia/Jakarta

#jwt
app.ticket-system.jwt.jwt-secret=${JWT_SECRET:}
app.ticket-system.jwt.app-name=ticket-system
app.ticket-system.jwt.expired=${JWT_EXPIRED:3600}

#seed super admin
app.seed.super-admin.username=${SEED_ADMIN_USERNAME:superadmin}
app.seed.super-admin.password=${SEED_ADMIN_PASSWORD:}